### ISSUE TITLE
Occasional incorrect exit code 1 from process

### ISSUE THREAD

**Issue by mikehardy** [invertase/nodejs-google-java-format#2]
I don't see any issues open on the upstream google-java-format repository about this, but I have seen it locally and in CI, occasionally despite known good input, an exit code will be returned, for example:

```
$ google-java-format --set-exit-if-changed --replace --glob="packages/**/android/**/*.java"
Error: google-java-format exited with exit code 1.
    at errorFromExitCode (/home/runner/work/react-native-firebase/react-native-firebase/node_modules/google-java-format/index.js:19:10)
    at ChildProcess.<anonymous> (/home/runner/work/react-native-firebase/react-native-firebase/node_modules/google-java-format/index.js:121:40)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

I am using the retry-action (https://github.com/nick-invision/retry/) in my CI in the meantime, to good effect.

Any help diagnosing this would be greatly appreciated!

**Comment by Babsvik** [comment]
I also get this @mikehardy 

I first tried with openjdk (v19) - that didn't work at all for me. 
So I downgraded to openjdk@11 and now it works, but I am getting this occasional exit codes. 

No worries for me, I just run the command again. Found this issue while searching for a solution so figured I'd chip in that the same is happening to me.
